GET http://localhost:3000/todos/?status=TO%20DO

### SCENARIO-2
GET http://localhost:3000/todos/?priority=HIGH

### SCENARIO-3
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

### SCENARIO-4
GET http://localhost:3000/todos/?search_q=Buy

### SCENARIO-5
GET http://localhost:3000/todos/?category=WORK&status=DONE


### SCENARIO-6
GET http://localhost:3000/todos/?category=HOME

###  SCENARIO-7
GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH


### API2
GET http://localhost:3000/todos/1/


### API3
GET http://localhost:3000/agenda/?date=2020-12-22

### API4

POST http://localhost:3000/todos/
Content-Type: application/json

{
 "id": 6,
 "todo": "Finalize event theme",
 "priority": "LOW",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-02-22"
}

###  API 5
PUT http://localhost:3000/todos/2/

### Scenario 1 
PUT http://localhost:3000/todos/2/
Content-Type: application/json

{ "status": "DONE" }


### Scenario 2 
PUT http://localhost:3000/todos/3/
Content-Type: application/json

{ "priority": "HIGH" }


### Scenario 3
PUT http://localhost:3000/todos/2/
Content-Type: application/json

{
"todo": "Clean the garden"
}

### Scenario 4 
PUT http://localhost:3000/todos/2/
Content-Type: application/json

{ "category": "LEARNING" }


### Scenario 5 
PUT http://localhost:3000/todos/2/
Content-Type: application/json

{ "dueDate": "2021-01-12" }



### api6
DELETE http://localhost:3000/todos/1/
